//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingBirthday.WP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.StirlingBirthday.WP.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no birthdays found in your contacts..
        /// </summary>
        public static string AllEmptyText {
            get {
                return ResourceManager.GetString("AllEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllPivotHeader {
            get {
                return ResourceManager.GetString("AllPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STIRLING BIRTHDAY.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Home.
        /// </summary>
        public static string CallHomeMenuText {
            get {
                return ResourceManager.GetString("CallHomeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Mobile.
        /// </summary>
        public static string CallMobileMenuText {
            get {
                return ResourceManager.GetString("CallMobileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Work.
        /// </summary>
        public static string CallWorkMenuText {
            get {
                return ResourceManager.GetString("CallWorkMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How sad!.
        /// </summary>
        public static string EmptyLeadText {
            get {
                return ResourceManager.GetString("EmptyLeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends had a birthday in the past month..
        /// </summary>
        public static string PastEmptyText {
            get {
                return ResourceManager.GetString("PastEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past.
        /// </summary>
        public static string PastPivotHeader {
            get {
                return ResourceManager.GetString("PastPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmailMenuText {
            get {
                return ResourceManager.GetString("SendEmailMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMSMenuText {
            get {
                return ResourceManager.GetString("SendSMSMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends have a birthday in the next month..
        /// </summary>
        public static string UpcomingEmptyText {
            get {
                return ResourceManager.GetString("UpcomingEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upcoming.
        /// </summary>
        public static string UpcomingPivotHeader {
            get {
                return ResourceManager.GetString("UpcomingPivotHeader", resourceCulture);
            }
        }
    }
}
