//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shane.Church.StirlingBirthday.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shane.Church.StirlingBirthday.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other apps by Shane Church.
        /// </summary>
        public static string AboutOtherAppsLabel {
            get {
                return ResourceManager.GetString("AboutOtherAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this app.
        /// </summary>
        public static string AboutReviewLabel {
            get {
                return ResourceManager.GetString("AboutReviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add contact.
        /// </summary>
        public static string AddContactLabel {
            get {
                return ResourceManager.GetString("AddContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task updates the Stirling Birthday live tile with upcoming birthday information..
        /// </summary>
        public static string AgentDescription {
            get {
                return ResourceManager.GetString("AgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for this application have been disabled by the user..
        /// </summary>
        public static string AgentsDisabledByUserError {
            get {
                return ResourceManager.GetString("AgentsDisabledByUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device does not support background agents, so this feature will be disabled..
        /// </summary>
        public static string AgentsNotSupportedError {
            get {
                return ResourceManager.GetString("AgentsNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no birthdays found in your contacts..
        /// </summary>
        public static string AllEmptyText {
            get {
                return ResourceManager.GetString("AllEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AllPivotHeader {
            get {
                return ResourceManager.GetString("AllPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Shane Church 2014.
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a simple app to remind you of your friends&apos; birthdays with a beautiful live tile.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STIRLING BIRTHDAY.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial of this application has expired. Do you want to purchase the application now? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string AppTrialEnd_MessageBox_Content {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string AppTrialEnd_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Expired.
        /// </summary>
        public static string AppTrialEnd_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppTrialEnd_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the ad-supported trial version of this application. Do you want to purchase the application now to remove the ads? If you choose Yes - you will be redirected to the marketplace..
        /// </summary>
        public static string AppTrialReminder_MessageBox_Content {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string AppTrialReminder_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Reminder.
        /// </summary>
        public static string AppTrialReminder_MessageBox_Title {
            get {
                return ResourceManager.GetString("AppTrialReminder_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Home.
        /// </summary>
        public static string CallHomeMenuText {
            get {
                return ResourceManager.GetString("CallHomeMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Mobile.
        /// </summary>
        public static string CallMobileMenuText {
            get {
                return ResourceManager.GetString("CallMobileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Work.
        /// </summary>
        public static string CallWorkMenuText {
            get {
                return ResourceManager.GetString("CallWorkMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} days.
        /// </summary>
        public static string DaysTextPlural {
            get {
                return ResourceManager.GetString("DaysTextPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0} day.
        /// </summary>
        public static string DaysTextSingular {
            get {
                return ResourceManager.GetString("DaysTextSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has encountered a problem. I am sorry for the inconvenience.
        ///
        ///I would appreciate your assistance by sending the prepared error report. This will help with resolving the problem faster..
        /// </summary>
        public static string Diagnostics_MessageBox_Content {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string Diagnostics_MessageBox_Title {
            get {
                return ResourceManager.GetString("Diagnostics_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Birthday! I hope you have a great day!.
        /// </summary>
        public static string EmailBodyText {
            get {
                return ResourceManager.GetString("EmailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How sad!.
        /// </summary>
        public static string EmptyLeadText {
            get {
                return ResourceManager.GetString("EmptyLeadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I improve this application so that you would be willing to rate it 5 stars in the marketplace?.
        /// </summary>
        public static string FeedbackContent {
            get {
                return ResourceManager.GetString("FeedbackContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I make it better?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to give feedback.
        /// </summary>
        public static string GiveFeedbackButton {
            get {
                return ResourceManager.GetString("GiveFeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is {0}&apos;s birthday! Happy Birthday {1}!.
        /// </summary>
        public static string HappyBirthdayShare {
            get {
                return ResourceManager.GetString("HappyBirthdayShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Birthday!.
        /// </summary>
        public static string HappyBirthdayText {
            get {
                return ResourceManager.GetString("HappyBirthdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string MBCancelText {
            get {
                return ResourceManager.GetString("MBCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string MBNoText {
            get {
                return ResourceManager.GetString("MBNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string MBOkText {
            get {
                return ResourceManager.GetString("MBOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string MBYesText {
            get {
                return ResourceManager.GetString("MBYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no thanks.
        /// </summary>
        public static string NoThanksButton {
            get {
                return ResourceManager.GetString("NoThanksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open people app.
        /// </summary>
        public static string OpenPeopleAppLabel {
            get {
                return ResourceManager.GetString("OpenPeopleAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends had a birthday in the past month..
        /// </summary>
        public static string PastEmptyText {
            get {
                return ResourceManager.GetString("PastEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to past.
        /// </summary>
        public static string PastPivotHeader {
            get {
                return ResourceManager.GetString("PastPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        public static string PinLabel {
            get {
                return ResourceManager.GetString("PinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        public static string PluralAgeText {
            get {
                return ResourceManager.GetString("PluralAgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate me.
        /// </summary>
        public static string RateLabel {
            get {
                return ResourceManager.GetString("RateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would love to hear from you! If you like the app, please rate it on the marketplace and share your feedback..
        /// </summary>
        public static string RateReminder_MessageBox_Content {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this reminder again.
        /// </summary>
        public static string RateReminder_MessageBox_SkipFurtherRemindersMessage {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_SkipFurtherRemindersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string RateReminder_MessageBox_Title {
            get {
                return ResourceManager.GetString("RateReminder_MessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string SendEmailMenuText {
            get {
                return ResourceManager.GetString("SendEmailMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SendSMSMenuText {
            get {
                return ResourceManager.GetString("SendSMSMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareMenuText {
            get {
                return ResourceManager.GetString("ShareMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year old.
        /// </summary>
        public static string SingularAgeText {
            get {
                return ResourceManager.GetString("SingularAgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to technical support/feedback email.
        /// </summary>
        public static string TechnicalSupportEmailLabel {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stirling Birthday Feedback.
        /// </summary>
        public static string TechnicalSupportEmailSubject {
            get {
                return ResourceManager.GetString("TechnicalSupportEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayText {
            get {
                return ResourceManager.GetString("TodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many background agents have been enabled. Please go to the settings application to disable other agents before enabling the Stirling Birthday agent..
        /// </summary>
        public static string TooManyAgentsError {
            get {
                return ResourceManager.GetString("TooManyAgentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} day(s) left..
        /// </summary>
        public static string TrialReminderPeriodMessage {
            get {
                return ResourceManager.GetString("TrialReminderPeriodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} time(s) left..
        /// </summary>
        public static string TrialReminderUsageCountMessage {
            get {
                return ResourceManager.GetString("TrialReminderUsageCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No friends have a birthday in the next month..
        /// </summary>
        public static string UpcomingEmptyText {
            get {
                return ResourceManager.GetString("UpcomingEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upcoming.
        /// </summary>
        public static string UpcomingPivotHeader {
            get {
                return ResourceManager.GetString("UpcomingPivotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An upgrade is available! Do you want to install the upgrade now?.
        /// </summary>
        public static string UpgradeText {
            get {
                return ResourceManager.GetString("UpgradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Available!.
        /// </summary>
        public static string UpgradeTitle {
            get {
                return ResourceManager.GetString("UpgradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Stirling Birthday!.
        /// </summary>
        public static string WelcomeCaption {
            get {
                return ResourceManager.GetString("WelcomeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for downloading Stirling Birthday!
        ///
        ///This app uses the information in the People hub on your Windows Phone. 
        ///
        ///Due to platform limitations, I am unable to add or edit birthdays within the app. To add or edit birthdays, open the People hub on your phone, add or edit a contact there, and then return to the app. The Birthday field is found under the Other category when editing contacts. 
        ///
        ///Thanks!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string YearsPlural {
            get {
                return ResourceManager.GetString("YearsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} year.
        /// </summary>
        public static string YearsSingular {
            get {
                return ResourceManager.GetString("YearsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
